[package]
name = "llama-cpp-rs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-cpp-sys = { git = "https://github.com/shadowmint/llama-cpp-sys.git", tag = "1.0.1" }
