[package]
name = "llama-cpp-rs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-cpp-sys = { path = "../llama-cpp-sys" }

[dev-dependencies]
regex = "1.9.3"